// const urlReactjs = "http://webbeta.4te.vn";
//const urlReactjs = "http://dev-web-4te.crmdvs.vn";
// const urlReactjs = "http://truyxuat.sopetgasone.com.vn";
const urlReactjs = "http://localhost:8080";
const urlChangePass = urlReactjs + "/#/changepassword";
const urlChangInformationUser = urlReactjs + "/#/changeinforuser";
const urlSeeDetailDataExport = urlReactjs + "/#/seetailddataexport";
const urlDetailHistoryImport = urlReactjs + '/#/seetailhistoryImport';
const urlCreateCalenderInpector = urlReactjs + '/#/createCalenderInspector';
export { urlChangePass, urlChangInformationUser, urlSeeDetailDataExport, urlDetailHistoryImport, urlCreateCalenderInpector };
